# Generated by Django 6.0.6 on 2026-06-23 20:23

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("asset_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("asset_name", models.CharField(max_length=150)),
                ("asset_description", models.TextField()),
                (
                    "asset_category",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("OT", "OT"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MAINTENANCE", "Maintenance"),
                            ("RETIRED", "Retired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cia_confidentiality",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cia_integrity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cia_availability",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("asset_owner", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("risk_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("risk_description", models.TextField()),
                ("likelihood", models.IntegerField()),
                ("impact", models.IntegerField()),
                (
                    "risk_rating",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("likelihood"), "*", models.F("impact")
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "risk_treatment",
                    models.CharField(
                        choices=[
                            ("Modify", "Modify"),
                            ("Retain", "Retain"),
                            ("Avoid", "Avoid"),
                            ("Share", "Share"),
                        ],
                        max_length=10,
                    ),
                ),
                ("review_date", models.DateField()),
                (
                    "risk_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("MITIGATED", "Mitigated"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="users.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mitigation",
            fields=[
                (
                    "mitigation_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("action_description", models.TextField()),
                ("target_date", models.DateField()),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("NOT STARTED", "Not Started"),
                            ("IN PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT STARTED",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField()),
                ("effectiveness_review_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitigations",
                        to="users.risk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskControl",
            fields=[
                (
                    "risk_control_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("control_code", models.CharField(max_length=50)),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="users.risk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                            ("LOGIN", "LOGIN"),
                        ],
                        max_length=10,
                    ),
                ),
                ("entity_name", models.CharField(max_length=100)),
                ("entity_id", models.CharField(max_length=50)),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                ("action_details", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "action_type", "action_date"],
                        name="idx_audit_logs_user_type_date",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(
                fields=["asset", "risk_status"], name="idx_risks_asset_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="risk",
            constraint=models.CheckConstraint(
                condition=models.Q(("likelihood__gte", 1), ("likelihood__lte", 5)),
                name="likelihood_between_1_and_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="risk",
            constraint=models.CheckConstraint(
                condition=models.Q(("impact__gte", 1), ("impact__lte", 5)),
                name="impact_between_1_and_5",
            ),
        ),
        migrations.AddIndex(
            model_name="mitigation",
            index=models.Index(
                fields=["risk", "target_date", "progress_status"],
                name="idx_mitigations_target_status",
            ),
        ),
    ]
