# Generated by Django 6.0.6 on 2026-06-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_criticality",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("INTERNAL", "Internal"),
                    ("CONFIDENTIAL", "Confidential"),
                    ("RESTRICTED", "Restricted"),
                ],
                default="Medium",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
