# Generated by Django 6.0.6 on 2026-06-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_asset_asset_criticality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="asset_id",
            new_name="asset",
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_criticality",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                max_length=20,
            ),
        ),
    ]
