# Generated by Django 6.0.6 on 2026-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_asset_id_asset_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="annex_control",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="risk",
            name="risk_category",
            field=models.CharField(
                choices=[
                    ("DEFAULT DATA", "Default Data"),
                    ("CYBERSECURITY", "Cybersecurity"),
                    ("OPERATIONAL", "Operational"),
                    ("SAFETY", "Safety"),
                    ("COMPLIANCE", "Compliance"),
                    ("PHYSICAL_SECURITY", "Physical Security"),
                    ("ENVIRONMENT", "Environment"),
                ],
                default="DEFAULT DATA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="risk_owner",
            field=models.CharField(default="", max_length=100),
        ),
    ]
