# Generated by Django 6.0.6 on 2026-06-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_risk_annex_control_risk_risk_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk",
            name="risk_treatment",
            field=models.CharField(
                choices=[
                    ("MODIFY", "Modify"),
                    ("RETAIN", "Retain"),
                    ("AVOID", "Avoid"),
                    ("SHARE", "Share"),
                ],
                max_length=10,
            ),
        ),
    ]
