# Generated by Django 6.0.6 on 2026-07-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_risk_risk_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="entity_id",
            field=models.CharField(max_length=100),
        ),
    ]
