# Generated by Django 6.0.6 on 2026-07-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_auditlog_entity_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "CREATE"),
                    ("UPDATE", "UPDATE"),
                    ("DELETE", "DELETE"),
                    ("LOGIN", "LOGIN"),
                    ("LOGOUT", "LOGOUT"),
                ],
                max_length=10,
            ),
        ),
    ]
